/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class SimpleFile */

#ifndef _Included_SimpleFile
#define _Included_SimpleFile
struct Hjava_lang_String;

typedef struct ClassSimpleFile {
#define SimpleFile_separatorChar 62L
    struct Hjava_lang_String *path;
    long fd;
} ClassSimpleFile;
HandleTo(SimpleFile);

extern /*boolean*/ long SimpleFile_open(struct HSimpleFile *);
extern void SimpleFile_close(struct HSimpleFile *);
extern long SimpleFile_read(struct HSimpleFile *,HArrayOfByte *,long);
extern long SimpleFile_write(struct HSimpleFile *,HArrayOfByte *,long);
#endif
