/* DO NOT EDIT THIS FILE - it is machine generated */
#include <StubPreamble.h>

/* Stubs for class SimpleFile */
/* SYMBOL: "SimpleFile/open()Z", Java_SimpleFile_open_stub */
stack_item *Java_SimpleFile_open_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long SimpleFile_open(void *);
	_P_[0].i = SimpleFile_open(_P_[0].p);
	return _P_ + 1;
}
/* SYMBOL: "SimpleFile/close()V", Java_SimpleFile_close_stub */
stack_item *Java_SimpleFile_close_stub(stack_item *_P_,struct execenv *_EE_) {
	extern void SimpleFile_close(void *);
	(void) SimpleFile_close(_P_[0].p);
	return _P_;
}
/* SYMBOL: "SimpleFile/read([BI)I", Java_SimpleFile_read_stub */
stack_item *Java_SimpleFile_read_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long SimpleFile_read(void *,void *,long);
	_P_[0].i = SimpleFile_read(_P_[0].p,((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
/* SYMBOL: "SimpleFile/write([BI)I", Java_SimpleFile_write_stub */
stack_item *Java_SimpleFile_write_stub(stack_item *_P_,struct execenv *_EE_) {
	extern long SimpleFile_write(void *,void *,long);
	_P_[0].i = SimpleFile_write(_P_[0].p,((_P_[1].p)),((_P_[2].i)));
	return _P_ + 1;
}
