/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class HelloWorldApplet */

#ifndef _Included_HelloWorldApplet
#define _Included_HelloWorldApplet
struct Hjava_awt_peer_ComponentPeer;
struct Hjava_awt_Container;
struct Hjava_awt_Color;
struct Hjava_awt_Font;
struct Hjava_awt_Component;
struct Hjava_awt_LayoutManager;
struct Hjava_applet_AppletStub;

typedef struct ClassHelloWorldApplet {
    struct Hjava_awt_peer_ComponentPeer *peer;
    struct Hjava_awt_Container *parent;
    long x;
    long y;
    long width;
    long height;
    struct Hjava_awt_Color *foreground;
    struct Hjava_awt_Color *background;
    struct Hjava_awt_Font *font;
    /*boolean*/ long visible;
    /*boolean*/ long enabled;
    /*boolean*/ long valid;
    long ncomponents;
    struct HArrayOfObject *component;
    struct Hjava_awt_LayoutManager *layoutMgr;
/* Inaccessible static: panelLayout */
    struct Hjava_applet_AppletStub *stub;
} ClassHelloWorldApplet;
HandleTo(HelloWorldApplet);

#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
