/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class collections_Dynarray */

#ifndef _Included_collections_Dynarray
#define _Included_collections_Dynarray
struct Hcollections_Predicate;
struct Hjava_lang_Object;

typedef struct Classcollections_Dynarray {
    long version_;
    struct Hcollections_Predicate *screener_;
    long count_;
#define collections_Dynarray_minCapacity 16L
    struct HArrayOfObject *array_;
} Classcollections_Dynarray;
HandleTo(collections_Dynarray);

#endif
